FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    linux-libc-dev \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

COPY src/pico_teleop_robot /src/pico_teleop_robot
RUN pip install --no-cache-dir /src/pico_teleop_robot

ENTRYPOINT ["pico-robot"]
